FROM oven/bun:1

WORKDIR /usr/src/app

# Install OpenSSL (needed for Prisma)
RUN apt-get update && apt-get install -y openssl libssl-dev

# Copy monorepo dependencies
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

# Copy backend app
COPY ./apps/backend ./apps/backend

# Install dependencies and generate Prisma client
RUN bun install
RUN bun run db:generate

EXPOSE 8080

# Start backend
CMD ["bun", "run", "start:backend"]
